[package]
name = "binance-history-scrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
indicatif = "0.17.7"
ureq = "2.9.1"
zip = "0.6.6"
csv = "1.3.0"
time = "0.3.31"

[build-dependencies]
winres = "0.1.12"
